import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const css = (): string => readFileSync('src/styles.css', 'utf-8').replace(/\s+/g, ' ')
const workspaceCss = (): string => readFileSync('src/workspace.css', 'utf-8').replace(/\s+/g, ' ')
const benchmarksCss = (): string => readFileSync('src/BenchmarksRoute.css', 'utf-8').replace(/\s+/g, ' ')
const appSource = (): string => readFileSync('src/OpenAgronomyApp.tsx', 'utf-8')
const mainSource = (): string => readFileSync('src/main.tsx', 'utf-8')
const benchmarksRouteSource = (): string => readFileSync('src/BenchmarksRoute.tsx', 'utf-8')
const infoPagesSource = (): string => readFileSync('src/OpenAgronomyInfoPages.tsx', 'utf-8')

describe('Open Agronomy responsive workspace', () => {
  it('keeps conversation primary while exposing explicit view and field tabs', () => {
    const source = workspaceCss()
    const app = appSource()
    const main = mainSource()

    expect(main.indexOf("import './styles.css'")).toBeLessThan(main.indexOf("import './workspace.css'"))
    expect(app).toContain("useState<'chat' | 'split' | 'map'>('split')")
    expect(app).toContain('role="group" aria-label="Workspace view"')
    expect(app).toContain("view === 'chat' ? 'Conversation' : view === 'map' ? 'Map' : 'Together'")
    expect(app).toContain("aria-pressed={(workspaceView === 'split' && !wideWorkspace ? 'chat' : workspaceView) === view}")
    expect(app).toContain('onClick={() => setWorkspaceView(view)}')
    expect(app).toContain("page === 'fields'")
    expect(app).toContain('role="group" aria-label="Field information"')
    expect(app).toContain("tab === 'details' ? 'Overview' : tab === 'records' ? 'Records & soil tests' : 'Map context'")
    expect(app).toContain("hidden={fieldTab !== 'details'}")
    expect(app).toContain("hidden={fieldTab !== 'records'}")
    expect(app).toContain("hidden={fieldTab !== 'context'}")
    expect(source).toMatch(/\.workspace-shell \.analyze-workspace \{[^}]*grid-template-columns: minmax\(400px, 1\.55fr\) minmax\(280px, 1fr\)/)
    expect(source).toMatch(/\.workspace-shell \.chat-panel \{[^}]*grid-column: 1/)
    expect(source).toMatch(/\.workspace-shell \.map-stage \{[^}]*grid-column: 2/)
    expect(source).toMatch(/\.workspace-shell \.view-chat \.map-stage \{[^}]*display: none/)
    expect(source).toMatch(/\.workspace-shell \.view-map \.chat-panel \{[^}]*display: none/)
  })

  it('contains long content and keeps the map behind its mobile view control', () => {
    const source = workspaceCss()
    const mobile = source.slice(source.indexOf('@media (max-width: 1050px)'))

    expect(source).toMatch(/\.workspace-content \{[^}]*min-width: 0/)
    expect(source).toMatch(/\.workspace-shell \.chat-panel \{[^}]*min-width: 0/)
    expect(source).toMatch(/\.workspace-shell \.conversation-thread \{[^}]*overflow-y: auto; overflow-x: hidden/)
    expect(source).toMatch(/\.workspace-shell \.chat-message \{[^}]*max-width: 100%;[^}]*overflow-wrap: anywhere/)
    expect(source).toMatch(/\.workspace-shell \.formatted-answer pre \{[^}]*overflow: auto/)
    expect(mobile).toMatch(/\.workspace-shell \.analyze-workspace \{[^}]*grid-template-columns: minmax\(0, 1fr\)/)
    expect(mobile).toMatch(/\.workspace-shell \.analyze-workspace:not\(\.view-map\) \.map-stage \{[^}]*display: none/)
    expect(mobile).toMatch(/\.workspace-shell \.view-map \.map-stage \{[^}]*display: flex/)
    expect(mobile).toMatch(/\.workspace-shell \.workspace-view-switch \.view-split \{[^}]*display: none/)
  })

  it('provides keyboard focus targets and dialogs that fit small viewports', () => {
    const source = workspaceCss()
    const mobile = source.slice(source.indexOf('@media (max-width: 680px)'))
    const app = appSource()

    expect(source).toMatch(/\.workspace-shell button:focus-visible,[^}]*outline: 3px solid/)
    expect(source).toMatch(/\.workspace-view-switch button,[^}]*min-height: 34px/)
    expect(source).toMatch(/\.workspace-dialog \{[^}]*width: min\(560px, calc\(100vw - 32px\)\); max-height: calc\(100dvh - 40px\)/)
    expect(mobile).toMatch(/\.workspace-dialog, \.workspace-dialog\.wide \{[^}]*width: calc\(100vw - 16px\); max-height: calc\(100dvh - 16px\)/)
    expect(mobile).toMatch(/\.workspace-dialog \.field-grid \{[^}]*grid-template-columns: 1fr/)
    expect(app).toContain("if (event.key === 'Enter') void renameStoredField(stored)")
    expect(app).toContain("if (event.key === 'Escape') setRenamingFieldId('')")
  })

  it('keeps the benchmark page wired to the human review operations packet', () => {
    const app = appSource()
    const route = benchmarksRouteSource()
    const infoPages = infoPagesSource()
    const styles = css()
    const benchmarkStyles = benchmarksCss()

    expect(app).toContain("const APP_PAGES: Page[] = ['analyze', 'fields', 'evidence', 'benchmarks', 'sources', 'privacy', 'about']")
    expect(app).toContain("const BenchmarksRoute = lazy(() => import('./BenchmarksRoute')")
    expect(app).toContain("const LeafletFieldMap = lazy(() => import('./LeafletFieldMap')")
    expect(app).toContain("const FieldSyncPanel = lazy(() => import('./FieldSyncPanel'))")
    expect(app).toContain('<FieldSyncPanel')
    expect(app).toContain('Loading field map')
    expect(app).toContain('currentHashPage')
    expect(app).toContain("window.addEventListener('hashchange', syncPageFromHash)")
    expect(app).toContain("window.history.pushState(null, '', nextHash)")
    expect(app).toContain('Loading benchmark readiness')
    expect(app).toContain('<BenchmarksRoute />')
    expect(app).toContain("const OpenAgronomyInfoPages = lazy(() => import('./OpenAgronomyInfoPages'))")
    expect(app).toContain("page === 'privacy' || page === 'about'")
    expect(app).toContain('<OpenAgronomyInfoPages page={page} />')
    expect(app).toContain("['privacy', 'Privacy']")
    expect(app).toContain("['analyze', 'Workspace']")
    expect(app).toContain('aria-label="More pages"')
    expect(app).toContain("fieldName ? 'Ask about this field' : 'Let’s work through it.'")
    expect(app).not.toContain('<h2>Advice</h2>')
    expect(infoPages).toContain('function PrivacyPage()')
    expect(infoPages).toContain('Data use boundary for the public demo')
    expect(infoPages).toContain('Official AI AgriBench prompts never enter RAG, KG, screenshots, docs, or training artifacts')
    expect(app).toContain('function CredentialPreflightPanel')
    expect(app).toContain('<PublicAdapterReadinessPanel readiness={adapterReadiness} compact />')
    expect(app).toContain('<CredentialPreflightPanel readiness={adapterReadiness} />')
    expect(app).toContain('Credential preflight')
    expect(app).toContain('Variable names only. Secret values are never shown.')
    expect(app).toContain('PYTHONPATH=src:. python scripts/smoke_keyed_public_adapters.py --live')
    expect(app).toContain('curl -s http://127.0.0.1:8001/api/tools/public-adapter-readiness')
    expect(styles).toMatch(/\.privacy-page,[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.privacy-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.privacy-flow > div \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.privacy-grid,[^}]*grid-template-columns: 1fr/)
    expect(styles).toMatch(/\.credential-preflight-list \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.credential-preflight-list,[^}]*grid-template-columns: 1fr/)
    expect(route).toContain('/api/benchmarks/human-review-outcomes')
    expect(route).toContain('/api/benchmarks/artifacts/')
    expect(route).toContain("apiGet<PublicDemoAcceptanceChecklist>(benchmarkArtifactHref('public-demo-acceptance-checklist-json'))")
    expect(route).toContain("apiGet<LiveSourceQaPacket>(benchmarkArtifactHref('live-source-qa-packet-json'))")
    expect(route).toContain('data-testid="public-demo-acceptance-panel"')
    expect(route).toContain('data-testid="live-source-qa-panel"')
    expect(route).toContain('Acceptance status')
    expect(route).toContain('Live source QA')
    expect(route).toContain('Regional matrix')
    expect(route).toContain('AI AgriBench submission')
    expect(route).toContain('acceptanceOpenGates.length')
    expect(route).toContain('acceptanceCommandRows.map')
    expect(route).toContain("benchmarkArtifactHref('public-demo-acceptance-checklist')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-acceptance-checklist-json')")
    expect(route).toContain('Acceptance checklist')
    expect(route).toContain("benchmarkArtifactHref('live-source-qa-packet')")
    expect(route).toContain("benchmarkArtifactHref('live-source-qa-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('live-source-qa-packet-builder')")
    expect(route).toContain('Live source QA')
    expect(route).toContain("benchmarkArtifactHref('mobile-app-qa-packet')")
    expect(route).toContain("benchmarkArtifactHref('mobile-app-qa-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('mobile-app-qa-packet-builder')")
    expect(route).toContain('Mobile QA')
    expect(route).toContain("benchmarkArtifactHref('public-demo-artifact-bundle-manifest')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-artifact-bundle-manifest-json')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-artifact-bundle-builder')")
    expect(route).toContain('Artifact bundle')
    expect(route).toContain("benchmarkArtifactHref('human-review-quickstart')")
    expect(route).toContain("benchmarkArtifactHref('human-user-test-script')")
    expect(route).toContain("benchmarkArtifactHref('human-smoke-preflight-markdown')")
    expect(route).toContain("benchmarkArtifactHref('human-smoke-preflight')")
    expect(route).toContain("benchmarkArtifactHref('human-review-outcomes-template')")
    expect(route).toContain("benchmarkArtifactHref('human-review-batch-ingest-latest')")
    expect(route).toContain("benchmarkArtifactHref('human-review-batch-ingest-helper')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-rehearsal-prompts')")
    expect(route).toContain("benchmarkArtifactHref('heldout-gap-review-csv')")
    expect(route).toContain("benchmarkArtifactHref('heldout-gap-review-markdown')")
    expect(route).toContain("benchmarkArtifactHref('heldout-gap-review-json')")
    expect(route).toContain("reviewBatchArtifactId(batch.batch_id)")
    expect(route).toContain("human-review-batch-quickstart-smoke")
    expect(route).toContain('data-testid="human-review-execution-checklist"')
    expect(route).toContain('Quickstart smoke to gate check')
    expect(route).toContain('Confirm the Data availability panel, trace groups, regional context, source cards, and final answer all agree.')
    expect(route).toContain('ingest_human_review_batch.py --batch-csv human_review_batch_quickstart_smoke.csv')
    expect(route).toContain('Latest ingest:')
    expect(route).toContain('data-testid="human-review-ops"')
    expect(route).toContain('reviewActions.slice(0, 4)')
    expect(route).toContain('reviewBatches.slice(0, 4)')
    expect(route).toContain('reviewRecordIssues.slice(0, 4)')
    expect(route).toContain('P0 record issues')
    expect(route).toContain('records clean')
    expect(route).toContain('Submission answer hygiene')
    expect(route).toContain("benchmarkArtifactHref('submission-answer-hygiene-audit')")
    expect(route).toContain("benchmarkArtifactHref('submission-answer-hygiene-markdown')")
    expect(route).toContain("benchmarkArtifactHref('submission-answer-hygiene-high-risk-csv')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-current-pass')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-manifest')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-inspection-packet')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-inspection-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-inspection-packet-builder')")
    expect(route).toContain('Inspection packet')
    expect(route).toContain("benchmarkArtifactHref('aiagribench-leaderboard-request-packet')")
    expect(route).toContain("benchmarkArtifactHref('aiagribench-leaderboard-request-packet-json')")
    expect(route).toContain('data-testid="aiagribench-official-target"')
    expect(route).toContain('416 QA rows')
    expect(route).toContain('Public pages disagree on September 1 vs September 30, 2024')
    expect(route).toContain('leaderboard/join')
    expect(route).toContain("benchmarkArtifactHref('aiagribench-submission-dry-run-packet')")
    expect(route).toContain("benchmarkArtifactHref('aiagribench-submission-dry-run-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('aiagribench-submission-dry-run-submit-safe-sample')")
    expect(route).toContain("apiGet<ModelAdaptationReadiness>('/api/models/adaptation-readiness')")
    expect(route).toContain('data-testid="model-adaptation-readiness"')
    expect(route).toContain('New global LoRA')
    expect(route).toContain('Next valid experiment')
    expect(route).not.toContain('data-testid="public-domain-deep-coverage"')
    expect(route).toContain('Request packet')
    expect(route).toContain('Request JSON')
    expect(route).toContain('Official dry run')
    expect(route).toContain('data-testid="aiagribench-submission-dry-run"')
    expect(route).toContain('qna_id + answer only')
    expect(route).toContain('data-testid="heldout-gap-review"')
    expect(route).toContain('Held-out gap review')
    expect(route).toContain('not training, prompt, RAG/KG, or regex repair data')
    expect(route).toContain('data-testid="submission-answer-hygiene"')
    expect(route).toContain('data-testid="report-visual-qa"')
    expect(route).toContain('Report visual QA')
    expect(route).toContain('reportVisualQa.pdf_rerender_required')
    expect(route).toContain('reportVisualQa.pdf_render_status')
    expect(route).toContain('answerHygiene.high_risk_review_row_count')
    expect(benchmarkStyles).toMatch(/\.review-execution-checklist ol \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-gate-grid \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-readiness-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-command-list article \{[^}]*grid-template-columns: minmax\(130px, 0\.28fr\) minmax\(0, 1fr\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-gate-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.review-execution-checklist ol,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.review-operations \{[^}]*grid-template-columns: minmax\(280px, 0\.9fr\) minmax\(360px, 1\.1fr\)/)
    expect(benchmarkStyles).toContain('.review-record-issue-panel .review-blocker-list span')
    expect(benchmarkStyles).toMatch(/\.review-operations,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toContain('.heldout-gap-review-panel')
    expect(benchmarkStyles).toContain('.dry-run-panel')
    expect(benchmarkStyles).toContain('.deep-coverage-panel')
    expect(benchmarkStyles).toContain('.deep-smoke-readiness')
    expect(benchmarkStyles).toContain('.deep-smoke-attempt')
    expect(benchmarkStyles).toContain('.deep-smoke-gaps')
    expect(benchmarkStyles).toContain('.visual-qa-panel')
    expect(benchmarkStyles).toMatch(/\.hygiene-summary-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.dry-run-summary-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.deep-coverage-summary-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-gaps \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.hygiene-summary-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.dry-run-summary-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.deep-coverage-summary-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-gaps,[^}]*grid-template-columns: 1fr/)
  })

  it('fails closed when live benchmark and review packets are unavailable', () => {
    const route = benchmarksRouteSource()

    expect(route).toContain("suite: 'Benchmark data unavailable'")
    expect(route).toContain('The live benchmark API is unavailable; no bundled score snapshot is shown.')
    expect(route).toContain("score_warning: 'The live rehearsal packet is unavailable.'")
    expect(route).toContain("score_warning: 'The live review queue is unavailable.'")
    expect(route).toContain("automated_blocker_ids: ['benchmark_api_unavailable']")
    expect(route).toContain("status: 'no_go'")
    expect(route).toContain("status: 'unavailable'")
    expect(route).toContain('no submission state is inferred')
  })
})
