import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const css = (): string => readFileSync('src/styles.css', 'utf-8').replace(/\s+/g, ' ')
const finalMobileCss = (): string => {
  const source = css()
  return source.slice(source.lastIndexOf('@media (max-width: 820px)'))
}
const compactDesktopCss = (): string => {
  const source = css()
  return source.slice(source.lastIndexOf('@media (max-width: 1180px) and (min-width: 821px)'))
}
const benchmarksCss = (): string => readFileSync('src/BenchmarksRoute.css', 'utf-8').replace(/\s+/g, ' ')
const appSource = (): string => readFileSync('src/OpenAgronomyApp.tsx', 'utf-8')
const benchmarksRouteSource = (): string => readFileSync('src/BenchmarksRoute.tsx', 'utf-8')
const infoPagesSource = (): string => readFileSync('src/OpenAgronomyInfoPages.tsx', 'utf-8')

describe('Open Agronomy mobile layout CSS', () => {
  it('keeps the 820px breakpoint map-first while moving field management to its own page', () => {
    const source = css()
    const app = appSource()

    expect(source).toMatch(/@media \(max-width: 820px\)/)
    expect(app).toContain('className="mobile-workspace-tabs"')
    expect(app).toContain('href="#map-panel"')
    expect(app).not.toContain('href="#field-context-panel"')
    expect(app).toContain('href="#chat-panel"')
    expect(app).toContain("page === 'fields'")
    expect(app).toContain('id="field-context-panel"')
    expect(app).toContain('id="map-panel"')
    expect(app).toContain('id="chat-panel"')
    expect(source).toMatch(/\.mobile-workspace-tabs \{[^}]*display: none/)
    expect(source).toMatch(/\.mobile-workspace-tabs \{[^}]*position: sticky;[^}]*top: 0;[^}]*order: 0;[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
    expect(source).toMatch(/\.mobile-workspace-tabs a \{[^}]*min-height: 42px/)
    expect(source).toMatch(/\.demo-nav \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(source).toMatch(/\.map-workspace \{[^}]*padding: 8px 8px 76px/)
    expect(source).toMatch(/\.map-stage \{[^}]*order: 1/)
    const finalMobile = finalMobileCss()
    expect(finalMobile).toMatch(/\.chat-panel \{[^}]*order: 2;[^}]*height: calc\(100svh - 72px\);[^}]*min-height: 0/)
    expect(finalMobile).toMatch(/\.conversation-thread \{[^}]*min-height: 0;[^}]*max-height: none/)
    expect(finalMobile).toMatch(/\.chat-heading \.panel-kicker,[^}]*\.chat-heading \.agent-state \{[^}]*display: none/)
    expect(finalMobile).toMatch(/\.answer-receipt \{[^}]*margin: 0/)
    expect(finalMobile).toMatch(/\.answer-receipt \{[^}]*display: none/)
    expect(finalMobile).toMatch(/\.answer-receipt-summary > div:first-child > span \{[^}]*display: none/)
    // Desktop keeps the map usable while explicitly reserving a generous chat column.
    // This protects the current map/chat balance instead of the superseded layout.
    expect(source).toMatch(/\.analyze-workspace \{[^}]*grid-template-columns: minmax\(480px, 1\.12fr\) minmax\(500px, 0\.88fr\)/)
    expect(source).toMatch(/\.fields-workspace \{[^}]*display: block/)
  })

  it('uses touch-safe map controls and swipeable chat source cards on mobile', () => {
    const source = css()

    expect(source).toMatch(/\.conversation-thread \{[^}]*overflow-x: hidden;[^}]*overflow-y: auto/)
    expect(source).toMatch(/\.chat-message \{[^}]*box-sizing: border-box;[^}]*grid-template-columns: minmax\(0, 1fr\);[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*overflow-wrap: anywhere/)
    expect(source).toMatch(/\.chat-message > \* \{[^}]*min-width: 0;[^}]*max-width: 100%/)
    expect(source).toMatch(/\.formatted-answer > \*,[^}]*overflow-wrap: anywhere/)
    expect(source).toMatch(/\.formatted-answer pre \{[^}]*box-sizing: border-box;[^}]*max-width: 100%/)
    expect(source).toMatch(/\.map-toolbar \.map-actions \{[^}]*grid-template-columns: minmax\(0, 1fr\) auto/)
    expect(source).toMatch(/\.map-toolbar \.map-mode-control \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
    expect(source).toMatch(/\.map-primary-action \{[^}]*min-height: 44px/)
    expect(source).toMatch(/@media \(max-width: 420px\) \{[^}]*\.map-toolbar \.map-mode-control button \{[^}]*min-width: 0;[^}]*gap: 3px;[^}]*padding: 0 3px/)
    expect(source).toMatch(/\.map-toolbar \.map-mode-control button span \{[^}]*font-size: 12px;[^}]*white-space: nowrap/)
    expect(source).toMatch(/\.chat-panel \.tool-source-list \{[^}]*display: flex;[^}]*overflow-x: auto;[^}]*scroll-snap-type: x proximity/)
    expect(source).toMatch(/\.chat-panel \.tool-source-card \{[^}]*flex: 0 0 min\(88vw, 360px\);[^}]*scroll-snap-align: start/)
  })

  it('keeps a half-width desktop map-first without turning the map into a sidebar', () => {
    const compactDesktop = compactDesktopCss()
    const finalMobile = finalMobileCss()

    expect(compactDesktop).toMatch(/\.map-workspace \{[^}]*grid-template-columns: minmax\(0, 1\.15fr\) minmax\(340px, 0\.85fr\)/)
    expect(compactDesktop).toMatch(/\.chat-panel \{[^}]*grid-column: auto/)
    expect(compactDesktop).toMatch(/\.map-stage \{[^}]*min-height: 620px/)
    expect(compactDesktop).toMatch(/\.chat-panel \{[^}]*min-height: 620px/)
    expect(finalMobile).toMatch(/\.chat-panel \{[^}]*box-sizing: border-box;[^}]*gap: 6px;[^}]*padding: 8px/)
    expect(finalMobile).toMatch(/\.network-answer-state\.runtime_online \{[^}]*display: none/)
    expect(finalMobile).toMatch(/\.chat-panel \.chat-composer textarea \{[^}]*min-height: 72px/)
  })

  it('keeps the benchmark page wired to the human review operations packet', () => {
    const app = appSource()
    const route = benchmarksRouteSource()
    const infoPages = infoPagesSource()
    const styles = css()
    const benchmarkStyles = benchmarksCss()

    expect(app).toContain("const APP_PAGES: Page[] = ['analyze', 'fields', 'evidence', 'benchmarks', 'sources', 'privacy', 'about']")
    expect(app).toContain("const BenchmarksRoute = lazy(() => import('./BenchmarksRoute')")
    expect(app).toContain("const LeafletFieldMap = lazy(() => import('./LeafletFieldMap')")
    expect(app).toContain("const FieldSyncPanel = lazy(() => import('./FieldSyncPanel'))")
    expect(app).toContain('<FieldSyncPanel')
    expect(app.indexOf('<FieldSyncPanel')).toBeLessThan(app.indexOf("{page === 'analyze' ? ("))
    expect(app).toContain('Loading field map')
    expect(app).toContain('currentHashPage')
    expect(app).toContain("window.addEventListener('hashchange', syncPageFromHash)")
    expect(app).toContain("window.history.pushState(null, '', nextHash)")
    expect(app).toContain('Loading benchmark readiness')
    expect(app).toContain('<BenchmarksRoute />')
    expect(app).toContain("const OpenAgronomyInfoPages = lazy(() => import('./OpenAgronomyInfoPages'))")
    expect(app).toContain("page === 'privacy' || page === 'about'")
    expect(app).toContain('<OpenAgronomyInfoPages page={page} />')
    expect(app).toContain("['privacy', 'Privacy']")
    expect(app).toContain("['analyze', 'Workspace']")
    expect(app).toContain('aria-label="More pages"')
    expect(app).toContain('<h2>Ask about this field</h2>')
    expect(app).not.toContain('<h2>Advice</h2>')
    expect(infoPages).toContain('function PrivacyPage()')
    expect(infoPages).toContain('Data use boundary for the public demo')
    expect(infoPages).toContain('Official AI AgriBench prompts never enter RAG, KG, screenshots, docs, or training artifacts')
    expect(app).toContain('function CredentialPreflightPanel')
    expect(app).toContain('<PublicAdapterReadinessPanel readiness={adapterReadiness} compact />')
    expect(app).toContain('<CredentialPreflightPanel readiness={adapterReadiness} />')
    expect(app).toContain('Credential preflight')
    expect(app).toContain('Variable names only. Secret values are never shown.')
    expect(app).toContain('PYTHONPATH=src:. python scripts/smoke_keyed_public_adapters.py --live')
    expect(app).toContain('curl -s http://127.0.0.1:8001/api/tools/public-adapter-readiness')
    expect(styles).toMatch(/\.privacy-page,[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.privacy-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.privacy-flow > div \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.privacy-grid,[^}]*grid-template-columns: 1fr/)
    expect(styles).toMatch(/\.credential-preflight-list \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
    expect(styles).toMatch(/\.credential-preflight-list,[^}]*grid-template-columns: 1fr/)
    expect(route).toContain('/api/benchmarks/human-review-outcomes')
    expect(route).toContain('/api/benchmarks/artifacts/')
    expect(route).toContain("apiGet<PublicDemoAcceptanceChecklist>(benchmarkArtifactHref('public-demo-acceptance-checklist-json'))")
    expect(route).toContain("apiGet<LiveSourceQaPacket>(benchmarkArtifactHref('live-source-qa-packet-json'))")
    expect(route).toContain('data-testid="public-demo-acceptance-panel"')
    expect(route).toContain('data-testid="live-source-qa-panel"')
    expect(route).toContain('Acceptance status')
    expect(route).toContain('Live source QA')
    expect(route).toContain('Regional matrix')
    expect(route).toContain('AI AgriBench submission')
    expect(route).toContain('acceptanceOpenGates.length')
    expect(route).toContain('acceptanceCommandRows.map')
    expect(route).toContain("benchmarkArtifactHref('public-demo-acceptance-checklist')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-acceptance-checklist-json')")
    expect(route).toContain('Acceptance checklist')
    expect(route).toContain("benchmarkArtifactHref('live-source-qa-packet')")
    expect(route).toContain("benchmarkArtifactHref('live-source-qa-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('live-source-qa-packet-builder')")
    expect(route).toContain('Live source QA')
    expect(route).toContain("benchmarkArtifactHref('mobile-app-qa-packet')")
    expect(route).toContain("benchmarkArtifactHref('mobile-app-qa-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('mobile-app-qa-packet-builder')")
    expect(route).toContain('Mobile QA')
    expect(route).toContain("benchmarkArtifactHref('public-demo-artifact-bundle-manifest')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-artifact-bundle-manifest-json')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-artifact-bundle-builder')")
    expect(route).toContain('Artifact bundle')
    expect(route).toContain("benchmarkArtifactHref('human-review-quickstart')")
    expect(route).toContain("benchmarkArtifactHref('human-user-test-script')")
    expect(route).toContain("benchmarkArtifactHref('human-smoke-preflight-markdown')")
    expect(route).toContain("benchmarkArtifactHref('human-smoke-preflight')")
    expect(route).toContain("benchmarkArtifactHref('human-review-outcomes-template')")
    expect(route).toContain("benchmarkArtifactHref('human-review-batch-ingest-latest')")
    expect(route).toContain("benchmarkArtifactHref('human-review-batch-ingest-helper')")
    expect(route).toContain("benchmarkArtifactHref('public-demo-rehearsal-prompts')")
    expect(route).toContain("benchmarkArtifactHref('heldout-gap-review-csv')")
    expect(route).toContain("benchmarkArtifactHref('heldout-gap-review-markdown')")
    expect(route).toContain("benchmarkArtifactHref('heldout-gap-review-json')")
    expect(route).toContain("reviewBatchArtifactId(batch.batch_id)")
    expect(route).toContain("human-review-batch-quickstart-smoke")
    expect(route).toContain('data-testid="human-review-execution-checklist"')
    expect(route).toContain('Quickstart smoke to gate check')
    expect(route).toContain('Confirm the Data availability panel, trace groups, regional context, source cards, and final answer all agree.')
    expect(route).toContain('ingest_human_review_batch.py --batch-csv human_review_batch_quickstart_smoke.csv')
    expect(route).toContain('Latest ingest:')
    expect(route).toContain('data-testid="human-review-ops"')
    expect(route).toContain('reviewActions.slice(0, 4)')
    expect(route).toContain('reviewBatches.slice(0, 4)')
    expect(route).toContain('reviewRecordIssues.slice(0, 4)')
    expect(route).toContain('P0 record issues')
    expect(route).toContain('records clean')
    expect(route).toContain('Submission answer hygiene')
    expect(route).toContain("benchmarkArtifactHref('submission-answer-hygiene-audit')")
    expect(route).toContain("benchmarkArtifactHref('submission-answer-hygiene-markdown')")
    expect(route).toContain("benchmarkArtifactHref('submission-answer-hygiene-high-risk-csv')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-current-pass')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-manifest')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-inspection-packet')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-inspection-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('visual-qa-inspection-packet-builder')")
    expect(route).toContain('Inspection packet')
    expect(route).toContain("benchmarkArtifactHref('aiagribench-leaderboard-request-packet')")
    expect(route).toContain("benchmarkArtifactHref('aiagribench-leaderboard-request-packet-json')")
    expect(route).toContain('data-testid="aiagribench-official-target"')
    expect(route).toContain('416 QA rows')
    expect(route).toContain('Public pages disagree on September 1 vs September 30, 2024')
    expect(route).toContain('leaderboard/join')
    expect(route).toContain("benchmarkArtifactHref('aiagribench-submission-dry-run-packet')")
    expect(route).toContain("benchmarkArtifactHref('aiagribench-submission-dry-run-packet-json')")
    expect(route).toContain("benchmarkArtifactHref('aiagribench-submission-dry-run-submit-safe-sample')")
    expect(route).toContain("apiGet<ModelAdaptationReadiness>('/api/models/adaptation-readiness')")
    expect(route).toContain('data-testid="model-adaptation-readiness"')
    expect(route).toContain('New global LoRA')
    expect(route).toContain('Next valid experiment')
    expect(route).not.toContain('data-testid="public-domain-deep-coverage"')
    expect(route).toContain('Request packet')
    expect(route).toContain('Request JSON')
    expect(route).toContain('Official dry run')
    expect(route).toContain('data-testid="aiagribench-submission-dry-run"')
    expect(route).toContain('qna_id + answer only')
    expect(route).toContain('data-testid="heldout-gap-review"')
    expect(route).toContain('Held-out gap review')
    expect(route).toContain('not training, prompt, RAG/KG, or regex repair data')
    expect(route).toContain('data-testid="submission-answer-hygiene"')
    expect(route).toContain('data-testid="report-visual-qa"')
    expect(route).toContain('Report visual QA')
    expect(route).toContain('reportVisualQa.pdf_rerender_required')
    expect(route).toContain('reportVisualQa.pdf_render_status')
    expect(route).toContain('answerHygiene.high_risk_review_row_count')
    expect(benchmarkStyles).toMatch(/\.review-execution-checklist ol \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-gate-grid \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-readiness-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-command-list article \{[^}]*grid-template-columns: minmax\(130px, 0\.28fr\) minmax\(0, 1fr\)/)
    expect(benchmarkStyles).toMatch(/\.acceptance-gate-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.review-execution-checklist ol,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.review-operations \{[^}]*grid-template-columns: minmax\(280px, 0\.9fr\) minmax\(360px, 1\.1fr\)/)
    expect(benchmarkStyles).toContain('.review-record-issue-panel .review-blocker-list span')
    expect(benchmarkStyles).toMatch(/\.review-operations,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toContain('.heldout-gap-review-panel')
    expect(benchmarkStyles).toContain('.dry-run-panel')
    expect(benchmarkStyles).toContain('.deep-coverage-panel')
    expect(benchmarkStyles).toContain('.deep-smoke-readiness')
    expect(benchmarkStyles).toContain('.deep-smoke-attempt')
    expect(benchmarkStyles).toContain('.deep-smoke-gaps')
    expect(benchmarkStyles).toContain('.visual-qa-panel')
    expect(benchmarkStyles).toMatch(/\.hygiene-summary-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.dry-run-summary-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.deep-coverage-summary-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-grid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-gaps \{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
    expect(benchmarkStyles).toMatch(/\.hygiene-summary-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.dry-run-summary-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.deep-coverage-summary-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-grid,[^}]*grid-template-columns: 1fr/)
    expect(benchmarkStyles).toMatch(/\.deep-smoke-gaps,[^}]*grid-template-columns: 1fr/)
  })

  it('fails closed when live benchmark and review packets are unavailable', () => {
    const route = benchmarksRouteSource()

    expect(route).toContain("suite: 'Benchmark data unavailable'")
    expect(route).toContain('The live benchmark API is unavailable; no bundled score snapshot is shown.')
    expect(route).toContain("score_warning: 'The live rehearsal packet is unavailable.'")
    expect(route).toContain("score_warning: 'The live review queue is unavailable.'")
    expect(route).toContain("automated_blocker_ids: ['benchmark_api_unavailable']")
    expect(route).toContain("status: 'no_go'")
    expect(route).toContain("status: 'unavailable'")
    expect(route).toContain('no submission state is inferred')
  })
})
