type DemoPage = {
  id: string
  title: string
  purpose: string
  items: string[]
}

export const phase6HomepageExplanation =
  'Open Agronomy Agent helps users structure agronomy questions, add field context, retrieve relevant public sources, surface missing data, and generate transparent advisory-style answers and reports. It is decision support for discussion, not product/rate advice, label authority, field diagnosis, or a replacement for local agronomists.'

const demoPages: DemoPage[] = [
  {
    id: 'landing',
    title: 'Landing',
    purpose: 'Explain the public sandbox without overstating readiness.',
    items: [
      'Open Agronomy Agent is decision support for discussion, not field diagnosis or product/rate advice.',
      'The canonical demo path uses the server harness with RAG, tools, trace capture, and report export.',
      'Synthetic sample fields are available for safe first-run exploration.',
    ],
  },
  {
    id: 'how-it-works',
    title: 'How It Works',
    purpose: 'Show the visible chain from field context to evidence-backed answer.',
    items: [
      'The app routes the question, retrieves public evidence, records caveats, and asks for missing data.',
      'Reports expose source references, field context used, model version, corpus version, and prompt/context policy version.',
      'Feedback can create reviewed eval candidates only when consent and review gates are satisfied.',
    ],
  },
  {
    id: 'what-it-is-not',
    title: 'What It Is Not',
    purpose: 'Keep launch claims inside the safety boundary.',
    items: [
      'Not a certified agronomist, legal authority, label source, or replacement for local recommendations.',
      'Not a product/rate engine and not a field-specific diagnosis without verified field evidence.',
      'Not a guarantee that every source is current, complete, or locally applicable.',
    ],
  },
  {
    id: 'source-coverage',
    title: 'Data Source Coverage',
    purpose: 'Describe coverage and known source gaps.',
    items: [
      'Public extension/government-style sources are preferred for RAG-visible guidance.',
      'Data-source audit exports summarize license state, ingest state, indexed chunks, and gaps.',
      'Request source additions or takedowns with the source URL, crop/region scope, publisher, and coverage issue.',
      'Private uploads remain scoped to the workspace and are excluded from public source claims.',
    ],
  },
  {
    id: 'known-limitations',
    title: 'Known Limitations',
    purpose: 'List gaps users should understand before trying the demo.',
    items: [
      'Coverage varies by crop, region, source freshness, and available field context.',
      'High-risk product, legal, label, and rate questions require external local authority.',
      'Browser local preview is disabled by default and is not the canonical answer path.',
    ],
  },
  {
    id: 'prompt-library',
    title: 'Prompt Library',
    purpose: 'Give safe example prompts for the sandbox.',
    items: [
      'Nutrient and water-quality risk: frame runoff exposure and missing measurements.',
      'Low pH and lime planning: ask for buffer pH, soil texture, crop, and local recommendation basis.',
      'Plant-health triage: request symptom pattern, crop stage, weather, photos, and affected area.',
    ],
  },
  {
    id: 'sample-reports',
    title: 'Sample Reports',
    purpose: 'Point users to useful report artifacts generated by the app.',
    items: [
      'Thread report: public answer, field context, evidence, caveats, and next steps.',
      'Field context brief: user-entered field profile, known unknowns, and data quality meter.',
      'Demo eval snapshot: honest eval summary, eval limitations, model version, corpus version, and prompt/context policy version.',
    ],
  },
  {
    id: 'privacy-data-use',
    title: 'Privacy and Data Use',
    purpose: 'Make trace, feedback, export, and deletion behavior understandable.',
    items: [
      'Account export packages accessible records; object-store bytes and embedding vectors are excluded.',
      'Training candidates require consent and review gates; raw hidden prompts are not exported publicly.',
      'Deleted attachment metadata can remain visible for retention evidence until purge policy runs.',
    ],
  },
  {
    id: 'feedback-help',
    title: 'Feedback and Help',
    purpose: 'Give users a path for corrections and support.',
    items: [
      'Use feedback to flag wrong route, missing source, unsafe certainty, or bad local fit.',
      'Human corrections and ideal answers are reviewer inputs, not automatic model changes.',
      'Support requests should include report id, thread id, and a short description of the issue.',
    ],
  },
  {
    id: 'changelog-contribute',
    title: 'Changelog and Contribute',
    purpose: 'Show what changed and where collaborators can help.',
    items: [
      'Phase 6 adds report exports, field-context quality, RUM telemetry, account export, and WebGPU probing.',
      'Contribution areas: source coverage, eval review, accessibility QA, and launch-page copy review.',
      'Incident runbook owners must be assigned before public launch.',
    ],
  },
]

export function PublicDemoPages() {
  return (
    <section data-testid="public-demo-pages">
      <h2>Public Demo Pages</h2>
      <p data-testid="phase6-homepage-explanation">{phase6HomepageExplanation}</p>
      <nav aria-label="Public demo page index">
        {demoPages.map((page) => (
          <a key={page.id} href={`#${page.id}`}>
            {page.title}
          </a>
        ))}
      </nav>
      {demoPages.map((page) => (
        <article key={page.id} id={page.id} data-testid={`public-page-${page.id}`}>
          <h3>{page.title}</h3>
          <p>{page.purpose}</p>
          <ul>
            {page.items.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </article>
      ))}
    </section>
  )
}
